### ISSUE TITLE
Subvariants?

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#23]
We're starting to pile up a lot of variants of assumptions and schemes. E.g., the various versions of parallelization, SIDH/B-SIDH, etc.

We may consider regrouping variants as subfields of a main object. E.g.:

```yaml
parallelization:
  name:
    long: Parallelization
  aliases:
    - short: GA-CDH
      long: Group Action Computational Diffie-Hellman
  references:
    Cou06: 'https://eprint.iacr.org/2006/291'
  comment:
    The anaologue of CDH for Group Actions.
  variants:
    ordinary:
      reduces_to:
        - vector>ordinary
    supersingular:
      references:
        CD19: 'https://eprint.iacr.org/2019/1404'
      reduces_to:
        - vector>supersingular
      comments: Introduced for CSIDH
    oriented:
      references:
        CK20: 'https://eprint.iacr.org/2020/985'
        Wes21: 'https://eprint.iacr.org/2021/1583'
      reduces_to:
        - vector>oriented
```

This requires some thinking on the semantics (e.g., does it make sense to have `reduces_to` for the main object?) and the presentation (foldable rows?), though. Low priority.
