### ISSUE TITLE
Underline for link in attacks looks weird in the superscript

### ISSUE THREAD

**Issue by GiacomoPope** [issikebrokenyet/issikebrokenyet.github.io#30]
<img width="381" alt="Screenshot 2022-08-27 at 4 49 14 pm" src="https://user-images.githubusercontent.com/44242839/187037689-cf0be7ae-dfac-494e-aca9-c7b6763aa74f.png">

**Comment by GiacomoPope** [comment]
This isn't an issue with firefox, and adding `text-underline-position: under;` then makes Safari well behaved but Chrome is still weird.

We can emulate a better underline with 

```css
.complexity a{
    color: inherit;
    text-decoration: none;
    border-bottom: 1px solid;
}
```

I have pushed this to `better-underlines`

<img width="356" alt="Screenshot 2022-08-27 at 6 22 10 pm" src="https://user-images.githubusercontent.com/44242839/187041231-0ded292c-43e7-4955-ac42-a751580515a9.png">
`
