### ISSUE TITLE
Typo in complexity for Delfs Galbraith?

### ISSUE THREAD

**Issue by GiacomoPope** [issikebrokenyet/issikebrokenyet.github.io#32]
```yml
delfs-galbraith:
  name:
    short: DG
    long: Delfs-Galbraith
  complexity: exp(1/2)
  references:
    DG13: "https://arxiv.org/abs/1310.7789"
  comment: >-
    $\exp(1/4)$ reduction of the supersingular isogeny path problem to
    the vectorization problem for supsersingular curves over
    $\mathbb{F}_p$.
```
    
 Pretty sure `complexity: exp(1/2)` should be `complexity: exp(1/4)`? (from the paper's abstract) but wanted to double check before editing it, as I wasn't sure if this was the specific attack for curves over F_p, or the full attack which first looks for curves over F_p then performs the e^1/4 attack which i think still has complexity e^1/2?
